### ISSUE TITLE
cannot compile facade

### ISSUE THREAD

**Issue by compasses** [fluencelabs/ethdenver-hackathon#2]
Hi, recently i have tried some examples follow https://github.com/fluencelabs/ethdenver-hackathon/blob/main/web3-examples/Readme.md
but, the build.sh not work for me. After  study, i found the  facade project cannot compile,  before i have tried the greeting example.
many such errors ：
```
error[E0034]: multiple applicable items in scope
   --> /Users/xxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/field.rs:801:12
    |
801 |                     if M::BITS > T::Mem::BITS {
    |                           ^^^^ multiple `BITS` found
    |
note: candidate #1 is defined in the trait `BitMemory`
   --> /Users/xxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/mem.rs:44:2
    |
44  |     const BITS: u8 = mem::size_of::<Self>() as u8 * 8;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: candidate #2 is defined in the trait `IsNumber`
   --> /Users/xxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/funty-1.2.0/src/lib.rs:144:2
    |
144 |     const BITS: u32;
    |     ^^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #1
    |
801 |                     if BitMemory::BITS > T::Mem::BITS {
    |                        ^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #2
    |
801 |                     if IsNumber::BITS > T::Mem::BITS {

```

The fluence project attracted me a lot, so i wanna dive in.
Big thanks.

**Comment by folex** [comment]
Hi! Thanks for reaching out :)

I found the problem! Seems like one of the transitive dependencies has broken, and `cargo update` took the broken version. I've removed `cargo update` from the build.sh, now it should work.

But you should reset `Cargo.lock` files before trying, cuz `cargo update` has changed them. You can easily revert all changes by running the following in `ethdenver-hackathon` directory
```
git reset --hard
git pull
```

And then simply try `build.sh` again.

**Comment by compasses** [comment]
> build.sh

that's work. thanks.
